- azure-functions-gradle-plugin/build.gradle
see https://blog.gradle.org/plugin-portal-update
> Fix security issue: Plugin Portal Security CVE-2020-7599

- azure-functions-gradle-plugin/README.md
- azure-functions-gradle-plugin/build.gradle
- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/AzureFunctionsExtension.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/GradleFunctionContext.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/IAppServiceContext.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/configuration/auth/AzureClientFactory.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- Enable app insights support for Gradle plugins for Azure Functions
- Update azure tools common to 0.3.0, fix deprecated methods
> Enable app insights support for Gradle plugins for Azure Functions

- azure-functions-gradle-plugin/build.gradle
- azure-functions-gradle-plugin/gradle.properties
Remove SNAPSHOT, prepare for release
> Prepare for release

- azure-functions-gradle-plugin/CHANGELOG.md
Update change log for version 1.3.0
> Update change log for version 1.3.0

- azure-functions-gradle-plugin/build.gradle
> Bump dependencies

- azure-functions-gradle-plugin/build.gradle
- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/task/DeployTask.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/task/IFunctionTask.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/task/LocalRunTask.java
> Support Java 11 runtime

- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/AzureFunctionsExtension.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/GradleFunctionContext.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/configuration/auth/AzureClientFactory.java
Support specify azure environment in gradle configuration
> Support specify azure environment in gradle configuration

- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/configuration/auth/AzureClientFactory.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/telemetry/TelemetryAgent.java
- Show environment name in console if use users didn't use global Azure environment.
- Add telemetries for azure environment, disable application insights and java version
> Show Azure environment and add telemetries

- azure-functions-gradle-plugin/build.gradle
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/AzureFunctionsExtension.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/GradleFunctionContext.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/configuration/auth/AzureClientFactory.java
Using environment variable in auth configuration instead of new parameters to set Azure environment.
> Using existing parameter for environment and better log

- azure-functions-gradle-plugin/build.gradle
- azure-functions-gradle-plugin/gradle.properties
Remove snapshot and update dependencies to stable version
> Prepare release

- azure-functions-gradle-plugin/CHANGELOG.md
- azure-functions-gradle-plugin/gradle.properties
Update release notes and bump version for next release
> Update release notes and bump version for next release

- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/GradleFunctionContext.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/configuration/auth/AzureClientFactory.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/task/DeployTask.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/task/LocalRunTask.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/task/PackageTask.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/task/PackageZipTask.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/telemetry/TelemetryAgent.java
Add missing telemetries for Functions gradle plugin
> Add missing telemetries for Functions gradle plugin

- azure-webapp-gradle-plugin/build.gradle
- azure-webapp-gradle-plugin/gradle.properties
- azure-webapp-gradle-plugin/settings.gradle
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/AzureWebappPlugin.java
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/AzureWebappPluginExtension.java
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/DeployTask.java
- azure-webapp-gradle-plugin/src/main/resources/ApplicationInsightsTemplate.xml
- azure-webapp-gradle-plugin/src/main/resources/schema/WebAppConfiguration.json
- settings.gradle
[AB#1855229](https://dev.azure.com/mseng/a4d27ce2-a42d-4b71-8eef-78cee9a9728e/_workitems/edit/1855229)
> [Task 1855229] add gradle webapp plugin

- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/AzureFunctionsPlugin.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/task/LocalRunTask.java
- azure-gradle-plugins-common/build.gradle
- azure-gradle-plugins-common/src/main/java/com/microsoft/azure/gradle/temeletry/TelemetryAgent.java
- azure-gradle-plugins-common/src/main/java/com/microsoft/azure/gradle/util/GradleAzureMessager.java
- azure-gradle-plugins-common/src/main/java/com/microsoft/azure/gradle/util/GradleProxyUtils.java
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/AzureWebappPlugin.java
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/DeployTask.java
fix some bugs in graldle plugin :
1. adjust gradle messager to fix the interrupted log caused by system.out.println 
2. adjust the prompt message in proxy
3. adjust the task dependency according to docker 
4. adjust the service plan resource group and name logic which are handled in app-service-lib
5. unify exception properties in webapp gradle plugin telemetry
> [Task 1855214] gradle messager adjustment

- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
Refers https://github.com/microsoft/azure-maven-plugins/pull/1669
> Refactor method for list functions and force refresh during retry

- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
Change retry policy to fixed delay and use int arry as indicator
> Change retry policy to fixed delay and use int arry as indicator

- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/PackageHandler.java
print '!!' when calling `messager.info("")`
1.  align empty with the first statement to be print
> fix the bug of print '!!' for empty string

- azure-functions-gradle-plugin/README.md
- azure-webapp-gradle-plugin/README.md
Add examples for azure plugin configuration with Gradle Kotlin DSL.
resolve #71
> Add kotlin dsl example to README.md

- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
[AB#1872013](https://dev.azure.com/mseng/a4d27ce2-a42d-4b71-8eef-78cee9a9728e/_workitems/edit/1872013)
> [Task  1872013] support default value for functions

- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- azure-webapp-gradle-plugin/gradle.properties
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/DeployTask.java
- build.gradle
[AB#1872013](https://dev.azure.com/mseng/a4d27ce2-a42d-4b71-8eef-78cee9a9728e/_workitems/edit/1872013)
> [Task 1872013] Support default value(region, runtime, pricing tier) for webapp and functions

- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/DeployTask.java
[AB#1872016](https://dev.azure.com/mseng/a4d27ce2-a42d-4b71-8eef-78cee9a9728e/_workitems/edit/1872016)
> [Task 1872016] add create webapp flag to webapp gradle plugin

- azure-functions-gradle-plugin/gradle.properties
- azure-gradle-plugins-common/gradle.properties
- azure-webapp-gradle-plugin/gradle.properties
- build.gradle
Bump version for toolkit lib to fix authentication issues for cloud shell
> Bump version for toolkit lib to fix authentication issues for cloud shell

- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/AzureFunctionsPlugin.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- azure-gradle-plugins-common/gradle.properties
- azure-gradle-plugins-common/src/main/java/com/microsoft/azure/gradle/common/GradleAzureTaskManager.java
- azure-webapp-gradle-plugin/gradle.properties
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/AzureWebappPlugin.java
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/DeployTask.java
- build.gradle
- Bump version for Gradle plugin and toolkits lib
- Add gradle task manager to fix NPE issues with azure resource refresh
> Bump version for Gradle plugin and toolkits lib

- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/AzureFunctionsPlugin.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- azure-gradle-plugins-common/gradle.properties
- azure-gradle-plugins-common/src/main/resources/bundles/com/microsoft/azure/toolkit/operation.properties
- azure-webapp-gradle-plugin/gradle.properties
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/AzureWebappPlugin.java
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/DeployTask.java
- build.gradle
- Fix service plan name did not work in Gradle configuration
- Fix null operation context warning during list function triggers
- Fix NULL operation context when configure Gradle project
- Remove SNAPSHOT, prepare for release
> Fix several bugs in endgame test and prepare for release

- azure-functions-gradle-plugin/CHANGELOG.md
- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- azure-gradle-plugins-common/gradle.properties
- azure-webapp-gradle-plugin/CHANGELOG.md
- azure-webapp-gradle-plugin/gradle.properties
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/DeployTask.java
- Remove SNAPSHOT, prepare for release
- Update change log for gradle plugins
- Fix parameter order for resource get
> Prepare release 202206

- azure-gradle-plugins-common/src/main/resources/bundles/com/microsoft/azure/toolkit/operation.properties
Add missing function operations, [AB#1964474](https://dev.azure.com/mseng/a4d27ce2-a42d-4b71-8eef-78cee9a9728e/_workitems/edit/1964474)
> Resolve issues in endgame tests

- azure-functions-gradle-plugin/CHANGELOG.md
- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/PackageHandler.java
- azure-gradle-plugins-common/gradle.properties
- azure-gradle-plugins-common/src/main/java/com/microsoft/azure/gradle/auth/GradleAuthHelper.java
- azure-webapp-gradle-plugin/CHANGELOG.md
- azure-webapp-gradle-plugin/gradle.properties
- build.gradle
- Upgrade default function extension bundle to v3
- Upgrade to latest azure toolkits lib and resolve compile issues
[AB#1974372](https://dev.azure.com/mseng/a4d27ce2-a42d-4b71-8eef-78cee9a9728e/_workitems/edit/1974372)
> Task #1974372] Add Java 17 support for Azure Functions 

- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
Update hint message for java version
> Update hint message for java version

- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/PackageHandler.java
Fix v2 functions java library was excluded during package with functions gradle plugin
> Fix lib exclude issue for gradle functions

- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/DeployHandler.java
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/handler/PackageHandler.java
- azure-gradle-plugins-common/gradle.properties
- azure-gradle-plugins-common/src/main/java/com/microsoft/azure/gradle/auth/GradleAuthHelper.java
- azure-webapp-gradle-plugin/gradle.properties
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/DeployTask.java
- build.gradle
Update default function extenison bundle version to v4
> [Task #2038041] Update default function extenison bundle version to v4

- azure-functions-gradle-plugin/gradle.properties
- azure-functions-gradle-plugin/src/main/java/com/microsoft/azure/plugin/functions/gradle/AzureFunctionsPlugin.java
- azure-webapp-gradle-plugin/gradle.properties
- azure-webapp-gradle-plugin/src/main/java/com/microsoft/azure/plugin/webapps/gradle/AzureWebappPlugin.java
Fix allowTelemetry did not work in web app gradle plugin, refers https://github.com/microsoft/azure-gradle-plugins/pull/169
> Fix telemetry issue for gradle plugins
